# Generated by Django 6.0.6 on 2026-08-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_teacher_student_teacher_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('teacher',), ('title',)},
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('phone_number',)},
        ),
    ]
