# Generated by Django 6.0.6 on 2026-08-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_subject_options_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('teacher', 'title')},
        ),
    ]
