# Generated by Django 6.0.6 on 2026-08-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('teacher',), ('title',)},
        ),
    ]
